### ISSUE TITLE
Could there be an easy way to inject subscriptions to events?

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#11]
I'm looking for a way to re-use subscription logic in event handlers. Is there something to achieve this?

cf https://github.com/day8/re-frame/blob/master/docs/FAQs/UseASubscriptionInAnEventHandler.md

Which I'm afraid is closely related to dereferencing Cells, though I wonder if it'd be possible to wrap event handling in a reactive context to make subscriptions available...

## Example
```clojure
(rd/reg-sub
 ::headers
 :<- [::user-agent] ;; these are runtime state so can't hardcode
 :<- [::session/id]
 (fn [ua ssid]
   (-> {"Content-Type" "application/json"
        "Accept" "application/json"}
       (assoc "User-Agent" ua)
       (assoc "Cookie" (str "service_session_cookie=" ssid)))))

(rd/reg-event-db
 ::update-profile
 (fn [db [_ json-data]]
   (assoc db :profile json-data)))

(rd/reg-event-fx
 ::fetch-profile
 :<- [::headers] ;; this does not exist now
 (fn [headers]
   {::http/get {:path "/api/myself.json"
                :on-success [::update-profile]}}))
```

**Comment by wkok** [comment]
Can `user-agent` and `session/id` not be read from `db` (global state)?

**Comment by valerauko** [comment]
In this example, they could be if I moved some `str` calls to the event that registers them in the db.

But in other cases it'd mean having to directly reuse the reg-sub handler function, which is okay if the only input is the app-db, but gets really chaotic as soon as there are derived input signals.

**Comment by valerauko** [comment]
I'll put up a PR in a few days with an inject-sub interceptor (it doesn't involve any Cell hacking)

**Comment by wkok** [comment]
It feels like the value of the subscription (watched by f/widget) should instead be dispatched to another event as an arg

**Comment by valerauko** [comment]
>another event as an arg

That is possible, but then every component that fires an event that might result in a HTTP call has to watch all these values that are irrelevant to the component itself. 

This is what I do at the moment for layered subs (`:bg-watch` so changes don't rebuild the component) but it's clutter

**Comment by wkok** [comment]
Merged the PR.
Thanks!
