### ISSUE TITLE
Support dispatch-n

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#14]
In re-frame :dispatch-n is a very convenient way to have one event-fx fire multiple other events (such as updating both session id and profile info after a successful login).

**Comment by wkok** [comment]
re-frame [has deprecated](https://day8.github.io/re-frame/api-builtin-effects/#dispatch-n) `:dispatch-n` in favour of using `:fx` with multiple `:dispatch` tuples: 

`:fx` is supported in re-dash 

https://day8.github.io/re-frame/api-builtin-effects/#fx

**Comment by valerauko** [comment]
Oh! I was not aware of that! So at this point this library supports both the "old" (fx keys directly in the result map) and the new (keys listed under :fx) way?

**Comment by wkok** [comment]
Correct
