### ISSUE TITLE
Events can't seem to alter the DB with 0.5.0

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#17]
I didn't have time to thoroughly debug, but I noticed that the result of events doesn't get persisted in the app-db.

On 0.4.0 the same code works without issue.

**Comment by valerauko** [comment]
I noticed that debug logs in widgets that were watching some subscription kept firing rapidly (like VERY rapidly) so I guess the app-db was being touched by something.

**Comment by wkok** [comment]
Could you try with v0.6.0?

**Comment by wkok** [comment]
v0.6.1 rather - fixes dynamic warnings

**Comment by valerauko** [comment]
Sadly the issue is present in 0.6.1 as well.

Trying to load data from SharedPreferences to app db ends up not loading the data to app db (I've added a debug dart:core/print to the persistence cofx and it doesn't show up on the debug logs either). The same code works with 0.4.0

**Comment by wkok** [comment]
Would you mind sharing some repro code?

We use shared_preferences loading into app-db for login/session related logic quite successfully.

**Comment by valerauko** [comment]
You're right, I can't repro this issue anymore. I'll open again if it reoccurs
