### ISSUE TITLE
Unexpected errors with reg-sub-as-cofx

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#18]
After registering a sub as cofx and trying to use it in an event handler, I was getting raw dart errors about trying to deref a LazySeq.

**Comment by wkok** [comment]
This seems to work as expected
```clojure
  (rd/reg-event-fx
    :count
    [(rd/inject-cofx :current-count)]
    (fn [{:keys [db current-count]} _]
      {:db (assoc db :current-count current-count)
       :log-count current-count}))

  (rd/reg-fx
   :log-count
   (fn [current-count]
     (println (str "The current-count is " current-count))))

  (rd/reg-sub
    :current-count
    (fn [db _]
      (:current-count db 123)))

  (rd/reg-sub-as-cofx [:current-count])
```

Outputs:
`The current-count is 123`

Maybe it's a version issue, have you tried with [v0.6.0](https://github.com/htihospitality/re-dash/releases/tag/0.6.0)?

**Comment by wkok** [comment]
v0.6.1 rather - fixes dynamic warnings

**Comment by valerauko** [comment]
I was getting this error because the subscription I was trying to inject had multiple input signals and so ran into the problem with #19

**Comment by wkok** [comment]
[v0.6.2](https://github.com/htihospitality/re-dash/releases/tag/0.6.2) released
Can we close this issue?
