### ISSUE TITLE
Support subscribing to subscriptions

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#2]
re-frame supports multiple layers of subscriptions and it only recomputes what's necessary. cf https://day8.github.io/re-frame/subscriptions/#why-layer-2-extractors

How difficult do you think this could be to port to re-dash?

**Comment by wkok** [comment]
Hello!

re-dash subscriptions internally uses ClojureDart Cells to watch for changes to a specific key in app-db, which similar to re-frame would only result in recomputing the view if the value subscribed to actually changed.

For example, given an app-db of
```clojure
{:name1 "Jack"
 :name2 "Jill"}
```
and the view subscribes to both names individually:
```clojure
(m/Column
   .children
   [(f/widget
      :watch [name1 (rd/subscribe [::model/get-name1])]
      (m/Text name1))
    (f/widget
      :watch [name2 (rd/subscribe [::model/get-name2])]
      (m/Text name2))])
```
then say only `:name1` is later changed from anywhere, we can be sure that the widget tree for `:name2` won't be recomputed 

Is there something more that multi layer subscriptions gives that I may be missing?

**Comment by wkok** [comment]
Ahh the link you shared refered to _layer 2 extractors_, but I think you're referring to _layer 3 materialised view_ mentioned here 
https://day8.github.io/re-frame/subscriptions/#the-four-layers

That requires some thinking, but yes, it would be nice to support

**Comment by valerauko** [comment]
Sorry, I meant to link to the _layer 3 materialised view_ part... 

In re-frame these "input functions" `subscribe` to other subscriptions. Is such a thing possible with cljd cells?

**Comment by wkok** [comment]
Yes, according to the ClojureDart cheatsheat cells can have other cells as their dependencies.

I'll experiment with it a bit in the next couple days

**Comment by wkok** [comment]
Promising news, in the [layer-3-materialised-view](https://github.com/htihospitality/re-dash/tree/layer-3-materialised-view) branch it works now where a subscription can subscribe to one other subscription (single signal) via the signals function

Not yet implemented is to support a vector or a map of signals, but at the moment this works:

```clojure

  ;; Layer 2 - Extractor
  (rd/reg-sub
    ::get-count
    (fn [db _query-vec]
      (:current-count db 0)))


  ;; Layer 3 - Materialised View
  (rd/reg-sub
    ::get-count-description

    ;; signals function
    (fn [query-v]
      (rd/subscribe [::get-count query-v]))

    ;; computation function
    (fn [get-count _query-v]
      (str "The count is exactly " get-count)))

```

**Comment by valerauko** [comment]
Awesome! If you'd rather, I can help from there and implement the rest of the feature?

**Comment by wkok** [comment]
I've just pushed a commit to this branch that adds support for a vector or map of signals
