### ISSUE TITLE
app-db changes lost with SharedPreferences interceptor

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#21]
See repro in repository: https://github.com/valerauko/re-dash-repro

Main issue around http/handle-success and session/update-ssid

**Comment by wkok** [comment]
Can you try with branch
 https://github.com/htihospitality/re-dash/tree/interceptor-await

I removed all the await calls as a test and that got your repro working with / without the persist interceptor, (along with the intended update-server event)

I suspect after the new events queue that got implemented a while ago, the need for async /await everywhere became superfluous, and this might have in turn led again to unordered event + interceptor execution as a consequence.

I still need to go through all the samples and tests to see if all is still working though, will continue again tomorrow.

**Comment by wkok** [comment]
Don't bother with the branch mentioned above, it resurfaced the coeffects-as-future bug.

I'm redesigning the events queue on top of [Queue](https://api.flutter.dev/flutter/dart-collection/Queue-class.html) - Initial testing looks promising

**Comment by wkok** [comment]
A better events queue implementation based on [Queue](https://api.flutter.dev/flutter/dart-collection/Queue-class.html) :
https://github.com/htihospitality/re-dash/tree/better-events-queue

All tests pass, all samples work, and this repro work
