### ISSUE TITLE
Support the `:->` shorthand

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#3]
A very common pattern is to just extract one value from the database, which in re-frame I'd do with `:->`

```clj
(reg-sub
 ::my-value
 :-> :some-keyword)
```

Writing just `:some-keyword` results in the subscription returning the parameter vector just like in re-frame, so supporting this syntax would be very helpful.

cf https://github.com/day8/re-frame/blob/dd18854498b6a5e51ed09bfcbd193d9dd84d8381/src/re_frame/core.cljc#L259-L271

I'd be happy to help implementing this

**Comment by wkok** [comment]
Interesting, I've never used this syntactic sugar before, but do see its benefit.
You're welcome to submit a PR for it
