### ISSUE TITLE
Consider adding "standard" interceptors from re-frame

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#35]
re-frame has a bunch of handy built-in interceptors. Consider lifting some of them into re-dash too

Personally I'd love to have `path` and `debug` 

cf https://day8.github.io/re-frame/api-re-frame.core/#interceptors

**Comment by valerauko** [comment]
I can help implementing it too

**Comment by wkok** [comment]
We already have a `path` and `debug`, see https://cljdoc.org/d/net.clojars.htihospitality/re-dash/1.0.0/doc/interceptors

**Comment by wkok** [comment]
Also `debug` is in the process of getting superpowers in the form of flutter devtools extension. It will be released hopefully soon.

**Comment by valerauko** [comment]
Oh wow sorry I didn't notice! Thanks!

**Comment by wkok** [comment]
FYI - [re-dash-inspector](https://github.com/htihospitality/re-dash-inspector)
