### ISSUE TITLE
Document development process

### ISSUE THREAD

**Issue by valerauko** [htihospitality/re-dash#4]
It'd be helpful if there was some documentation on how to help with developing.

* what's the general workflow like
* how to set up the dev env (what are the required tools)
* how to experiment with changes (since at this point there's no cljd repl)
* how to run tests

**Comment by wkok** [comment]
I've added a Development section to the readme:
https://github.com/htihospitality/re-dash#development

Does this help?

**Comment by valerauko** [comment]
Definitely! It lists all the stuff that weren't obvious to me. Thanks!
